app/Http/routes.php
      GridEncoder::encodeRequestedData(new \App\Models\BayRepository(new \App\Models\Bay()), Input::all());
  }]);
  Route::post('/bay-grid', ['as' => 'Bay Data', 'uses' => function() {
      GridEncoder::encodeRequestedData(new \App\Models\BayRepository(new \App\Models\Bay()), Input::all());
  }]);
  Route::post('/bay/crud', ['as' => 'Bay CRUD', 'uses' => function() {
    $bayController = new \App\Http\Controllers\BayController(new \App\Repositories\StationRepository, new \App\Repositories\BayRepository, new \App\Repositories\BaylocationRepository);

    switch (Input::get('oper'))
    {
      case 'add':
        return $bayController->saveBayInfo(Input::except('id', 'oper'));
        break;
      case 'edit':
        return $bayController->updateBayInfo(Input::get('BayId'), Input::except('id', 'oper'));
        break;
      case 'del':
        return  $bayController->deleteBayInfo(Input::get('id'));
        break;
    }
  }]);

  /**
   *-------------------------------
   * Host Crud
   *-------------------------------
  */
  Route::get('host', ['as' => 'Host Home', 'uses' => 'HostController@getIndex']);
  Route::get('host/{type}/{Id}/{redirect}', ['as' => 'Host Search', 'uses' => 'HostController@getIndex']);

  Route::get('host/{type}/{Id}/{redirect}/{station}/{bay}/{App}/{Status}', ['as' => 'Host Search', 'uses' => 'HostController@getIndex']);

  Route::get('host/{type}/{Id}/status/{statusVal}/branch/{id}', ['as' => 'Host Search', 'uses' => 'HostController@getIndex']);

  Route::get('host/{type}/{Id}', ['as' => 'Host Search', 'uses' => 'HostController@getIndex']);

  Route::post('/host-grid/region/{Id}/branch/{id}', ['as' => 'Host Data', 'uses' => function() {
      GridEncoder::encodeRequestedData(new \App\Models\HostRepository(new \App\Models\Host()), Input::all());
  }]);
  Route::post('/host-grid', ['as' => 'Host Data', 'uses' => function() {
      GridEncoder::encodeRequestedData(new \App\Models\HostRepository(new \App\Models\Host()), Input::all());
  }]);
  Route::post('/host/crud/redirect/true', ['as' => 'Host CRUD', 'uses' => function() {
    $hostController = new \App\Http\Controllers\HostController(new \App\Repositories\BayRepository, new \App\Repositories\HostRepository, new \App\Repositories\StationRepository, new \App\Repositories\CodeRepository);

    switch (Input::get('oper'))
    {
      case 'add':
        return $hostController->saveHostInfo(Input::except('id', 'oper'));
        break;
    }
  }]);
   Route::post('/host/crud', ['as' => 'Host CRUD', 'uses' => function() {
    $hostController = new \App\Http\Controllers\HostController(new \App\Repositories\BayRepository, new \App\Repositories\HostRepository, new \App\Repositories\StationRepository, new \App\Repositories\CodeRepository);
    switch (Input::get('oper'))
    {
      case 'add':
        return $hostController->saveHostInfo(Input::except('id', 'oper'));
        break;
      case 'edit':
        return $hostController->updateHostInfo(Input::get('HostId'), Input::except('id', 'oper'));
        break;
      case 'del':
        return  $hostController->deleteHostInfo(Input::get('id'));
        break;
    }
  }]);

  Route::get('stationinfo/{bay_id}', ['as' => 'Station Info',
        'uses' => 'BayController@getStationInfo']);
  Route::get('playerinfo/{bay_id}', 'HostController@getPlayerInfo');
  Route::get('appinfo/{bay_id}', 'HostController@getAppInfo');
  Route::get('bayInfo/{station_id}', 'HostController@getBayInfo');
  Route::get('getCount', 'BranchController@getCount');
  Route::get('getbayId/{host}', 'HostController@getHostname');
  Route::get('getHostId/{host}', 'HostController@getHostId');
  Route::get('getbayLocation/{bayId}/{hostid}', 'HostController@getBayLocationInfo');
  Route::post('redirectHostWithStation', 'BayController@redirectHostStation');

  Route::get('search/branchAutocomplete/{column}', 'BranchController@autocomplete');
  Route::get('search/regionAutocomplete/{column}', 'RegionController@autocomplete');
  Route::get('search/stationAutocomplete/{column}', 'StationController@autocomplete');
  Route::get('search/bayLocationAutocomplete/{column}', 'BaylocationController@autocomplete');
  Route::get('search/bayAutocomplete/{column}', 'BayController@autocomplete');
  Route::get('search/hostAutocomplete/{column}', 'HostController@autocomplete');
  

  /** New set of routes for HostVMC*/
  //Route::resource('host','HostVmcController');
  Route::get('host/create', 'HostVmcController@create');
 
  Route::get('bayDetails/{station_id}', 'HostVmcController@getBayInfoFromStation');
  //Route::get('host/{type}/{Id}/{redirect}/{station}/{bay}/{App}/{Status}', ['as' => 'Host Search', 'uses' => 'HostVmcController@getIndex']);
  Route::get('masterName/{bay_id}', 'HostVmcController@getPlayerInfo');
  Route::get('host/vmc', 'HostVmcController@storeData');







/** End Of Operations **/

//Admin Activity
  Route::group(
      ['prefix' => 'admin'],
      function () {
        Route::resource('roles', 'RoleController');

        Route::resource('users', 'AdminUsersController');

        Route::resource('permissions', 'PermissionController');
      }
  );

  /**
 * CCC
 * Customer Commitment Routes
 * Resource Controller for Create ,Update ,show and Delete
 */


  /**
  * Industry Grid
  */
  Route::resource('industry', 'IndustryController');
  Route::post('/industry-grid', ['as' => 'Industry Data', 'uses' => function() {
        GridEncoder::encodeRequestedData(
              new \App\Repositories\IndustryRepository(
                  new \App\Models\Industry())
              , Input::all());
  }]);
  Route::get('/industryList', 'AdvertiserController@getIndustryList');

  /**
  * Advertiser Grid
  */
  Route::resource('advertiser', 'AdvertiserController');
  
  Route::post('/advertiser-grid', ['as' => 'Advertiser Data', 'uses' => function() {
        GridEncoder::encodeRequestedData(
              new \App\Repositories\AdvertiserRepository(
                  new \App\Models\Advertiser())
              , Input::all());
  }]);

  Route::get('advertiser/create/redirect/{redirect}', 'AdvertiserController@create');
  Route::get('advertiser/create/redirect/{redirect}/{campaignId}', 'AdvertiserController@create');
  Route::get('advertiser/create/redirect/{redirect}/{pocampaignId}/edit/campaign/{campaignId}', 'AdvertiserController@create');
  Route::get('advertiser/create/redirect/{redirect}/{pocampaignId}/clone/campaign/{campaignId}', 'AdvertiserController@create');
  Route::get('advertiser/{id}/creatives', 'AdvertiserController@getCreatives');
  Route::get('checkadvertiser/{id}', 'AdvertiserController@checkAdvertiser');

  /**
  * Creative Grid
  */
  Route::resource('creative', 'CreativeController');
  Route::post('/creative-grid', ['as' => 'Creative Data', 'uses' => function() {
        GridEncoder::encodeRequestedData(
              new \App\Repositories\CreativeRepository(
                  new \App\Models\Creative(), new \App\Repositories\FfmpegRepository(),
                  new \App\Repositories\CodeRepository())
              , Input::all());
  }]);
  Route::get('deleteVideo/{filename}/{creativeId}', 'CreativeController@deleteVideoFromSource');
  Route::get('add/creative', 'CreativeController@addAnotherCreative');
  Route::get('updateUndoStatus/{creativeId}', 'CreativeController@updateStatusReview');
  Route::get('creativesFile/{creativeId}/{format}', 'CreativeController@fileDownload');
  Route::get('updateStatuses/{creative}/{status}', 'CreativeController@updateStatusFields');
  Route::get('checkPoAdv/{creativeId}', 'CreativeController@getPOCreatives');
  Route::get('googleDownload/{fileId}', 'CreativeController@googleFileDownload');


  /**
   * Purchase order grid
   */
  Route::resource('purchaseorder','PurchaseOrderController');
  /*Route::post('/po-grid', ['as' => 'purchase.order.data', 'uses' => function() {
        GridEncoder::encodeRequestedData(
              new App\Repositories\PurchaseOrderRepository(
                  new App\Models\PurchaseOrder())
              , Input::all());
  }]);*/
  Route::post('/po-grid', ['as' => 'PO', 'uses' => 'PurchaseOrderController@getPOGridData']);

  Route::get('purchaseorder/{poCampaignId}/edit/campaign/{cid}', 'PurchaseOrderController@poEdit');
  Route::get('purchaseorder/{poCampaignId}/add/campaign/', 'PurchaseOrderController@addNewCampaignForPO');
  Route::get('purchaseorder/pocampaign/{poCampaignId}/clone/campaign/{campaignId}', 
        'PurchaseOrderController@clonePO');
  Route::get('purchaseorder/pocampaign/{poCampaignId}/delete/campaign/{campaignId}', 
        'PurchaseOrderController@deletePO');
  Route::post('purchaseorderstore', 'PurchaseOrderController@store');
  Route::post('addcampaign', 'PurchaseOrderController@addCampaign');
  Route::get('purchaseOrder/{id}/{status}', 'PurchaseOrderController@getPoWithStatus');
  Route::get('purchaseOrder/{poid}/{campaignid}/{status}', 'PurchaseOrderController@getpoCampaignDetailsWithStatus');

  Route::post('purchaseOrder/validate/po', 'PurchaseOrderController@validatePO');
  Route::post('purchaseOrder/validate/campaign', 'PurchaseOrderController@validateCampaign');
  Route::post('purchaseOrder/validate/creative', 'PurchaseOrderController@validateCreative');

  /**
   * API ROUTES
  */

  Route::get('api/regions', 'Api\ApiController@getRegionDetails');
  Route::get('api/states', 'Api\ApiController@getStateDetails');
  Route::get('api/stations', 'Api\ApiController@getStationDetails');
  Route::get('api/region/{regionId}', 'Api\ApiController@getStationByRegionDetails');
  Route::get('api/state/{stateId}', 'Api\ApiController@getStationByStateDetails');
  Route::get('api/creative/{creativeId}', 'Api\ApiController@getCreativeDetailsById');
  Route::get('api/checkcreative/{creativeId}', 'Api\ApiController@checkCreativeToAddForCampaign');


/**
 * VMC config routes
 */
    Route::get('vmc-config', function(){
        return view('vmcConfig.vmc-config-new');
    });

app/Models/Creative.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Creative extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'Creative';
    protected $primaryKey = 'CreativeId';

    /**
     * The name of the "Updated At " column.
     *
     * @var string
     */
    const UPDATED_AT = 'UpdatedAt';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['CreativeName', 'AdvertiserId', 'FileName',
     'FileMetaData', 'Category1', 'Category2', 'UpdatedAt', 'Status', 'UpdatedBy'];

    public $timestamps = false;

    /**
    * Get user details, which belongs to Creative
    */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'UserId');
    }

    /**
    * Get Advertisers which are mapped with Creative
    */
    public function advertiser()
    {
        return $this->belongsTo('App\Models\Advertiser', 'AdvertiserId');
    }

    public function campaign()
    {
        return $this->belongsTo('App\Models\Campaign', 'CreativeId');
    }

     public function campaignCreative()
    {
        return $this->belongsTo('App\Models\CampaignCreative', 'CreativeId');
    }
}

resources/views/Creative/create.blade.php
@extends('layouts.ccctemplate')

@section('title')
    Creative
@endsection

@section('menu')
    @include('layouts.menu')
@endsection

@section('content')
    @can('Create Creative')
    {{--<div class="adminPanel customerGrid">--}}
    <div id="preLoaderBlock" style="display:none"><img class="preLoader" src="/assets/poassets/images/loader.gif"></div>
    <div class="adminPanel customerGrid">
      <form method="POST" action="/creative" name="creativeForm" id="creativeForm"
      enctype ='multipart/form-data', files = true>
      {!! Form::hidden('formRequestType', 'Submit', ['id'=>'formRequestType', 'class'=>'form-control']) !!}
          {!! csrf_field() !!}
        <h4 class="color-gray">{{"Add Creative"}}&nbsp;:</h4>
        <div class="clearfix fieldsWrapper col-md-8 col-xs-12">
          <div class="min-height-100 col-md-6 col-xs-12">
            {!! Form::label('creativeName','Creative Name',array('class' => 'color-blue')) !!}
            {!! Form::text('creativeName', old('creativeName'), ['class'=>'form-control']) !!}
          </div>
          <div class="min-height-100 col-md-6 col-xs-12">
            {!! Form::label('advertiser','Advertiser Name',array('class' => 'color-blue col-md-6')) !!}
            @can('Create Advertiser')
            <a href="/advertiser/create/redirect/creative" class="btn addAdvertiserBtn col-md-6 pull-right" onclick="javascript:return redirectAdvertiser('/advertiser/create/redirect/creative')"><i class="fa fa-plus-circle plus-icon"></i>&nbsp;Add Advertiser</a>
            @endcan
            <?php echo Form::select('advertiser', $advertiserArray, \Input::old('advertiser'),['class'=>'form-control']); ?>
          </div>

          {{--<div class="min-height-100 col-md-6 col-xs-12">
            {!! Form::label('file','Upload',array('class' => 'color-blue')) !!}
            {!! Form::file('file',null) !!}
          </div>--}}
           <div class="min-height-100 col-md-6 col-xs-12">
            {!! Form::label('Category1','Category 1',array('class' => 'color-blue')) !!}

            <?php echo Form::select('Category1', $categoryOneArray, \Input::old('Category1'),['class'=>'form-control']); ?>

         </div>
          <div class="min-height-100 col-md-6 col-xs-12">
            {!! Form::label('Category2','Category 2',array('class' => 'color-blue')) !!}

          <?php echo Form::select('Category2', $categoryTwoArray, \Input::old('Category2'),['class'=>'form-control']); ?>           
         </div>
        
            <div class="min-height-100 col-md-6 col-xs-12">
                <label class="color-blue">File</label>
                <a class="uploadAnchor form-control">
                    <span class="fileUploadIcon"></span>&nbsp;&nbsp;<span class="uploadFileLabel">Choose File</span>
                    <input type="file" name="file" onchange="getFileData(this);"/>
                </a>
                <div class="fileInfoBlock">
              <span>
               <span class="videoName col-md-12 col-xs-12 padding0"></span>
                {{--<span class="filePreviewIcon col-md-1 padding0" onclick="openVideoPreviewModal()"></span>--}}
               <!--  <span class="fileCloseIcon col-md-1 padding0" onclick="closeVideoPreviewModal()"></span> -->
              </span>
                </div>
            </div>
          <div class="min-height-100 col-md-12 col-xs-12">
            <div class="col-md-4 col-xs-12 text-center">
              <a href="{{{ URL::route('creative.index') }}}" class="btn btn-default cancelBtn color-blue col-md-12 col-xs-12">Cancel</a>
            </div>
            <div class="col-md-4 col-xs-12 text-center">
              <button id="submitButton" class="btn btn-default IndustrySubmitBtn col-md-12 col-xs-12 formSubmitUpdatePreloader" style="width: 100%;" type="submit">Submit</button>
            </div>
            <div class="col-md-4 col-xs-12 text-center">
              <button type="button" name="addAnother" id="addAnother" class="btn btn-default IndustrySubmitBtn col-md-12 col-xs-12 formSubmitUpdatePreloader" style="width: 100%;" >Add Another</button>
            </div>
          </div>
      </div>
      </form>
    </div>
    @endcan
    <script type="text/javascript">

      /**
       Add Another toggle
       */
      $('#addAnother').on('click', function() {        
          $('#formRequestType').val('addAnother');
          document.creativeForm.submit();          
      });

      $('#submitButton').on('click', function() {
          $('#formRequestType').val('Submit');
          document.creativeForm.submit();
      });


      /*to show uploaded file name*/
      function getFileData(myFile,creativeId){
          var file = myFile.files[0];
          var filename = file.name;
          $('.filePreviewIcon').show();
          $('.fileCloseIcon').show();
          $('.videoName').text(filename);
          console.log(file);
          console.log(creativeId);
      }

      //dropDownSorting();

      function clearfileName() {
        $('.fileInfoBlock .videoName').empty();
      }

    </script>
@stop

resources/views/Creative/edit.blade.php
@extends('layouts.ccctemplate')

@section('title')
  Advertiser
@endsection

@section('menu')
  @include('layouts.menu')
@endsection

@section('content')
  @include('layouts.validationAlert')
  <div class="logo"></div>
  @can('Update Creative')
  <div id="preLoaderBlock" style="display:none"><img class="preLoader" src="/assets/poassets/images/loader.gif"></div>
  <div class="industryContainer col-md-10 col-xs-12">
    {!! Form::open(['method' => 'PATCH','files' => true, 'route'=>['creative.update',$creative->CreativeId]]) !!}
    {!! csrf_field() !!}
    <h4 class="col-md-12 col-xs-12 color-gray">{{"Edit Creative "}}&nbsp;:</h4>
    <div class="clearfix fieldsWrapper col-md-8 col-xs-12">
      <div class="min-height-100 col-md-6 col-xs-12">
        {!! Form::label('creativeName','Creative Name',array('class' => 'color-blue')) !!}
        {!! Form::hidden('creativeId', Input::old('creativeId', $creative->CreativeId),['class'=>'form-control', 'id' => 'creativeId']) !!}
        {!! Form::hidden('GStatus', Input::old('GStatus', $creative->GStatus),['class'=>'form-control']) !!}
        {!! Form::text('creativeName', Input::old('creativeName', $creative->CreativeName),['class'=>'form-control']) !!}
      </div>
      <div class="min-height-100 col-md-6 col-xs-12">
        {!! Form::label('advertiser','Advertiser',array('class' => 'color-blue')) !!}
        @can('Create Advertiser')
        <a href="/advertiser/create/redirect/creative" class="btn addAdvertiserBtn col-md-6 pull-right" onclick="javascript:return redirectAdvertiser('/advertiser/create/redirect/creativeEdit/{{$creative->CreativeId}}')"><i class="fa fa-plus-circle plus-icon"></i>&nbsp;Add Advertiser</a>
        @endcan
        {!! Form::select('advertiser', $advertiserArray, $creative->AdvertiserId, ['class'=>'form-control']) !!}
      </div>
      <div class="min-height-100 col-md-6 col-xs-12">
        {!! Form::label('Category1','Category 1',array('class' => 'color-blue')) !!}
        {!! Form::select('Category1', $categoryOneArray, $creative->Category1, ['class'=>'form-control']) !!}
      </div>
      <div class="min-height-100 col-md-6 col-xs-12">
        {!! Form::label('Category2','Category 2',array('class' => 'color-blue')) !!}
        {!! Form::select('Category2', $categoryTwoArray, $creative->Category2, ['class'=>'form-control']) !!}
      </div>
      <div class="min-height-100 col-md-6 col-xs-12">
        <label class="color-blue">File</label>
        <a class="uploadAnchor form-control">
          <span class="fileUploadIcon"></span>&nbsp;&nbsp;<span class="uploadFileLabel">Choose File</span>
          <input id="editFileUpload" type="file" name="file" onchange="getFileData(this,'{{$creative->CreativeId}}');"/>
        </a>
        <div class="fileInfoBlock">
          <span class="editBlock" >
            
            @if($fileMetadata != null)
              <span class="videoName col-md-11 col-xs-10 padding0" id='uploadedFileinput' data-creativeid={{$creative->CreativeId}}>{!! $inputFileName !!}</span>
              @if($creative->Status == 'A' || $creative->Status == 'R')
                <span class="filePreviewIcon edit col-md-1 padding0" data-toggle="modal" data-target="#myModal"
                      onclick="openVideoPreviewModal('{{$creative->CreativeId}}','{!! $inputFileName !!}',
                              '{!! $fileMetadata->url !!}','{!! $fileMetadata->size !!}','{!! $fileMetadata->duration !!}','{!! $fileMetadata->extension !!}')"
                      style="display: block"></span>
              @else
                <span class="filePreviewIconDisabled col-md-1 col-xs-2 padding0" style="display: block"> </span>
              @endif
            @else
              <span class="videoName col-md-8 padding0"></span>
              <!-- <span class="fileCloseIcon col-md-1 padding0"  onclick="deleteVideo('{{$creative->CreativeId}}','{!! $inputFileName !!}')"></span>-->
              </span>
          @endif
        </div>
      </div>
      <div class="min-height-100 col-md-6 col-xs-12">
        {!! Form::label('Status','Status',array('class' => 'color-blue')) !!}
        {!! Form::select('Status', $status, $creative->Status , ['class'=>'form-control']) !!}
      </div>

      <div class="col-md-12 col-xs-12">
        <div class="col-md-6 col-xs-12 text-center">
          @if($inputFileName == null)
            <a href="{{{ URL::route('creative.index') }}}" id="cnl" disabled="disabled" class="btn btn-default cancelBtn color-blue col-md-12 col-xs-12">Cancel</a>
          @else
            <a href="{{{ URL::route('creative.index') }}}" id="cnl" class="btn btn-default cancelBtn color-blue col-md-12 col-xs-12">Cancel</a>
          @endif
        </div>
        <div class="col-md-6 col-xs-12 text-center">
          <button class="btn btn-default IndustrySubmitBtn col-md-12 col-xs-12 formSubmitUpdatePreloader">Update</button>
        </div>
      </div>


      {{--Video template--}}
              <!-- <div class="col-md-12 col-xs-12 modal fade" id="myModal" data-backdrop="static" data-keyboard="false">
        <div class="videoPreviewModal editPopUp">
          <a class="text-right col-md-push-10" data-dismiss="modal" onclick="closeVideoPreviewModal()"><img class="popUpClose" src="/assets/ccc-app/img/modalClose.png"/></a>
          <div class="videoPreviewModalPopUp videoEditPage">
            <div class="videoPreviewModal-content"></div>
            <div class="videoPreviewModal-footer">
              <div class="col-md-12">File Name:&nbsp;<span class="fileName"></span></div>
              <div class="col-md-12">File Size:&nbsp;<span class="fileSize"></span></div>
              <div class="col-md-12">Run Time:&nbsp;<span class="runTime"></span></div>
              <div class="col-md-12">Download:&nbsp;
              <span class="downloadIcon">
               <a class="videoDownload" href="">
                 <img class="downloadIcon" src="/assets/ccc-app/img/downloadVideoIcon.png">
               </a>
              </span>
              </div>
            </div>
          </div>
        </div>
      </div> -->

      </form>
    </div>

    <script type="text/javascript">
      function deleteVideo(creativeId,fileName){
        var ddis, vmc;
        ddis= $('#uploadedFileddis').text().length;
        vmc= $('#uploadedFilevmc').text().length;
        if(ddis > 0 && vmc > 0){
          message = "Are you sure, If u delete user InputFile, mp4 and mpg files will also be deleted?";
        }else {
          message = "Are you sure, you want to delete user InputFile?"
        }

        bootbox.confirm(message, function(result) {
          if(result == true) {
            $.ajax({type: "GET", url: "/deleteVideo/"+fileName+"/"+creativeId,
              success: function(results){

                if(results == "sucess"){
                  displayMessage("Successfully deleted file "+fileName, true);
                }else{
                  displayMessage("error failed to delete file "+fileName, false);
                }
                location.reload();
              }});
          }
        });
      }


      /*status toggle*/
      $('.payingYesBtn').on('click', function(){
        $('.payingNoBtn').removeClass('payingActive').addClass('color-gray');
        $('.payingYesBtn').addClass('payingActive');
        $('.payingNoBtn .IsPaying_no').removeAttr("name");
        $('.payingYesBtn .IsPaying_yes').attr("name","status");
      });
      $('.payingNoBtn').on('click', function(){
        $('.payingYesBtn').removeClass('payingActive').addClass('color-gray');
        $('.payingNoBtn').addClass('payingActive');
        $('.payingYesBtn .IsPaying_yes').removeAttr("name");
        $('.payingNoBtn .IsPaying_no').attr("name","status");
      });

      /*to show uploaded file name*/
      function getFileData(myFile){
        var file = myFile.files[0];
        var filename = file.name;

        $('.filePreviewIcon').show();
        $('.fileCloseIcon').show();
        $('.videoName').text(filename);

        $('.filePreviewIcon.edit').hide();
      }

      /*close video preview popup*/
      function closeVideoPreviewModal() {
        videojs(document.getElementById('my-video'), {}, function(){
        });
        var video=videojs("my-video");
        video.pause();
        $('.videoPreviewModal').hide();
      }

      /* open video preview popup
       creativeId, fileName, url, size, duration, extension */
      function openVideoPreviewModal(id,name,url,size,duration,extention){
        var w = 830, h = 640; // default sizes
        var t = h/2;var l = w/2;
        w = window.innerWidth - 200;
        h = window.innerHeight - 200;
        t =   h/2;l=w/2;
        var redirectGoogleDriveUrl="{{ config('gdrive.google_drive_webView_Path') }}"+url;

        window.open(redirectGoogleDriveUrl,'Google Drive Videos','width='+w+',height='+h+',top='+100+',' +
                'left='+100+',right='+100,'titlebar=yes');

        /* $('.videoEditPage .videoPreviewModal-content').html('<video id="my-video" class="video-js vjs-default-skin vjs-big-play-centered" ' +
         'controls preload="auto" width="430" height="300" poster="MY_VIDEO_POSTER.jpg" data-setup="{}">' +
         //             '<source src="'+videoUrl+'" type="'+type+'"></video>');
         '<source src="'+videoUrl1+'" type="'+type+'"></video>');

         $('.videoEditPage .fileName').text(name);
         $('.videoEditPage .fileSize').text(size);
         $('.videoEditPage .runTime').text(duration);
         $('.videoEditPage .videoDownload').attr('href',videoUrl);
         videojs(document.getElementById('my-video'), {}, function(){
         });
         $('.videoPreviewModal').show();*/
      }

       $("#advertiser").change(function (e) {
      
        var creativeId = $('#creativeId').val();
        checkPoAdvertiser(creativeId);

     });

    function checkPoAdvertiser(creativeId) {
      console.log('update master name');      
            $.ajax({
              url: '/checkPoAdv/'+creativeId,
              type: "GET",
              success: function (data) {                
                if(data != "")  {
                  var message = "Creative is associated with PO, You can't change Advertiser";
                    $('#form-success').addClass('alert alert-danger').html(message).show();

                    $("#form-success.alert.alert-danger").fadeTo(2000, 1000).slideUp(1000, function(){                        
                        $(this).hide();                        
                    });
                }

              }
            });
          }



    </script>
  @endcan
@stop